// DO NOT EDIT THIS FILE IT WILL BE OVERWRITTEN WITHOUT WARNING!!!!!!
//
/*
 * Mailgun.java
 *
 * Created on 23. Mai 2006, 14:34
 *
 * To change this template, choose Tools | Template Manager
 * and open the template in the editor.
 */

package org.agnitas.backend;

import java.sql.Connection;
import java.util.Hashtable;

/**
 *
 * @author mhe
 */
public interface Mailgun {
    /**
     * Initialize internal data
     * @param status_id the string version of the statusID to use
     * @param conn optional open database connection
     */
    void initializeMailgun (String status_id, Connection conn) throws Exception;

    /**
     * Change report in database
     * 
     * @param msg the new message in the DB report
     */
    void dbReport(String msg) throws Exception;

    /**
     * Execute an already setup mailgun
     * 
     * @param conn optional open database connection
     * @param opts options to control the execution beyond DB information
     */
    void executeMailgun(Connection conn, Hashtable opts) throws Exception;

    /**
     * Full execution of a mail generation
     * 
     * @param custid optional customer id
     * @return Status string
     */
    String fire(String custid) throws Exception;

    /**
     * Setup a mailgun without starting generation
     * 
     * @param conn optional open database connection
     * @param opts options to control the setup beyond DB information
     */
    void prepareMailgun(Connection conn, Hashtable opts) throws Exception;
}